In [26]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt

In [27]:
stocks = {
    "Reliance": "RELIANCE.NS",
    "Infosys": "INFY.NS",
    "HDFC_Bank": "HDFCBANK.NS",
    "ITC": "ITC.NS",
    "Maruti": "MARUTI.NS",
    "SBI": "SBIN.NS"
}

benchmark = "^NSEI"

In [28]:
for company, ticker in stocks.items():

    df = yf.download(
        ticker,
        start="2019-01-01",
        end="2025-12-31"
    )

    df.to_csv(f"../data/raw/{company}.csv")

    print(f"{company} data saved")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Reliance data saved
Infosys data saved

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

HDFC_Bank data saved
ITC data saved

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

Maruti data saved
SBI data saved

In [29]:
nifty = yf.download(
    benchmark,
    start="2019-01-01",
    end="2025-12-31"
)

nifty.to_csv("../data/raw/NIFTY50.csv")

print("NIFTY data saved")

[*********************100%***********************]  1 of 1 completed

NIFTY data saved

In [30]:
reliance = pd.read_csv(
    "../data/raw/Reliance.csv",
    skiprows=2
)

In [31]:
reliance.head()

         Date  Unnamed: 1  Unnamed: 2  Unnamed: 3  Unnamed: 4  Unnamed: 5
0  2019-01-01  496.196381  498.985034  491.371654  498.077624     9746670
1  2019-01-02  489.733887  498.852220  487.343625  493.319235    15628818
2  2019-01-03  483.691925  493.363540  482.518940  490.220816    16288287
3  2019-01-04  486.303436  488.870748  478.535167  485.750155    18516544
4  2019-01-07  489.003540  495.067675  487.343638  489.999475    12060290

In [32]:
reliance.columns = [
    "Date",
    "Close",
    "High",
    "Low",
    "Open",
    "Volume"
]

In [33]:
reliance.head()

         Date       Close        High         Low        Open    Volume
0  2019-01-01  496.196381  498.985034  491.371654  498.077624   9746670
1  2019-01-02  489.733887  498.852220  487.343625  493.319235  15628818
2  2019-01-03  483.691925  493.363540  482.518940  490.220816  16288287
3  2019-01-04  486.303436  488.870748  478.535167  485.750155  18516544
4  2019-01-07  489.003540  495.067675  487.343638  489.999475  12060290

In [34]:
reliance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1729 entries, 0 to 1728
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1729 non-null   object
 1   Close   1729 non-null   float64
 2   High    1729 non-null   float64
 3   Low     1729 non-null   float64
 4   Open    1729 non-null   float64
 5   Volume  1729 non-null   int64
dtypes: float64(4), int64(1), object(1)
memory usage: 81.2+ KB

In [35]:
reliance.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [36]:
reliance['Date']=pd.to_datetime(reliance['Date'])

In [37]:
reliance.head()

        Date       Close        High         Low        Open    Volume
0 2019-01-01  496.196381  498.985034  491.371654  498.077624   9746670
1 2019-01-02  489.733887  498.852220  487.343625  493.319235  15628818
2 2019-01-03  483.691925  493.363540  482.518940  490.220816  16288287
3 2019-01-04  486.303436  488.870748  478.535167  485.750155  18516544
4 2019-01-07  489.003540  495.067675  487.343638  489.999475  12060290

In [38]:
numeric_cols = ['Close', 'High', 'Low', 'Open', 'Volume']

reliance[numeric_cols] = reliance[numeric_cols].apply(pd.to_numeric)

In [39]:
reliance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1729 entries, 0 to 1728
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    1729 non-null   datetime64[ns]
 1   Close   1729 non-null   float64
 2   High    1729 non-null   float64
 3   Low     1729 non-null   float64
 4   Open    1729 non-null   float64
 5   Volume  1729 non-null   int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 81.2 KB

In [40]:
reliance.isnull().sum()

Date      0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

Creating Empty Master DataFrame

In [41]:
master_df=pd.DataFrame()

In [42]:
for company in stocks.keys():

    df = pd.read_csv(
        f"../data/raw/{company}.csv",
        skiprows=2
    )

    df.columns = [
        "Date",
        "Close",
        "High",
        "Low",
        "Open",
        "Volume"
    ]

    df['Company'] = company

    master_df = pd.concat([master_df, df])

In [43]:
master_df.head()

,Date,Close,High,Low,Open,Volume,Company
0,2019-01-01,496.196381,498.985034,491.371654,498.077624,9746670,Reliance
1,2019-01-02,489.733887,498.852220,487.343625,493.319235,15628818,Reliance
2,2019-01-03,483.691925,493.363540,482.518940,490.220816,16288287,Reliance
3,2019-01-04,486.303436,488.870748,478.535167,485.750155,18516544,Reliance
4,2019-01-07,489.003540,495.067675,487.343638,489.999475,12060290,Reliance

In [44]:
master_df.shape

(10374, 7)

In [45]:
master_df.to_csv(
    "../data/processed/master_stock_data.csv",
    index=False
)

In [46]:
master_df.head()

,Date,Close,High,Low,Open,Volume,Company
0,2019-01-01,496.196381,498.985034,491.371654,498.077624,9746670,Reliance
1,2019-01-02,489.733887,498.852220,487.343625,493.319235,15628818,Reliance
2,2019-01-03,483.691925,493.363540,482.518940,490.220816,16288287,Reliance
3,2019-01-04,486.303436,488.870748,478.535167,485.750155,18516544,Reliance
4,2019-01-07,489.003540,495.067675,487.343638,489.999475,12060290,Reliance

In [47]:
master_df.shape

(10374, 7)